# Why scouting and statistical analysis?

Statistical analysis of volleyball provides a valuable source of information for coaches and players about individual and team performances. Amongst other things it can help with:

- finding areas for improvement, areas that are working well (for individuals and teams as a whole)
- setting training goals
- assess game performance against training goals and team strategies
- assessing other teams to help prepare for upcoming matches
- testing hypotheses
- providing feedback to players
- generating match summaries and other information for media, team supporters, sponsors


Experienced coaches can and do make many of these assessments directly (without relying on an analyst), but analysis can help because it is more objective (it can provide quantitative assessments of performance, rather than subjective ones, and it is less prone to issues such as confirmation bias or a tendency to remember events that happened most recently at the expense of earlier events). It can also help assesss facets of play that can't easily be isolated by direct observation.


# General principles

It is helpful to separate the analytical process into several components:

1. Collecting match data (aka "scouting"). This is the raw play-by-play information that, on its own, does not provide actionable information. It's just raw data.
2. Turning the play-by-play data into actionable information, such as performance indicators that allow the team to evaluate individual player performance as well as the effectiveness of its offensive/defensive strategies. Scouting software packages generally provide this type of analytical functionality, but other options are also possible (specific apps for analysis, that are separate from the scouting software).
3. Communicating that information to relevant end-users and ensuring that the information being generated is appropriate for that end-user audience. Often the end-users are coaches and players, but in other cases might be sponsors or the general public, and so the information and level of detail that is needed for one audience might not be appropriate for another.

In this guide we're mostly focusing on #1, but bearing in mind that we need to deliver #2 and #3.

Parts 1 and 2 can be done on paper (not addressed here), or by computer.

## Principles

We want to collect our raw data in such a way that they are:

- as objective as possible, by minimizing subjective assessments by the scout.
- consistent (from one scout to another, and also over time for the same scout).
- appropriate for the specific needs of the users. For example, if the team is using a particular defensive strategy, the coach is likely to want to be able to evaluate it. The data that we collect and statistics that we generate should thus provide information that allows performance against that strategy, and the overall effectiveness of that strategy, to be evaluated.
- at the same time, we want to maximize the value of the data that we collect for different analyses (i.e. we can answer a range of different questions using these data, rather than collecting data that can only be used to answer a narrow range of questions). In particular we want to keep our options open for answering questions that we haven't thought of yet.
- is efficient, by balancing the demands on the scout against the value of the information that we ask them to collect. Every extra detail that we ask them to scout adds effort: does that extra detail actually give us valuable information? Can we avoid scouting it manually because it can be inferred or filled in automatically later?
- follows any established community norms or conventions, if necessary.


There is an important distinction between the *data being scouted* and the *information that can be extracted from those data*. In some cases the information that we want to report isn't directly obvious in the data that we are collecting, and some further analysis might be required to extract it.


## Software

### Scouting

a. DataVolley (https://www.dataproject.com/Products/EU/en/Volleyball/DataVolley4) is the well-established standard software, and is used by many national and professional teams. It is capable of recording all match information that you are ever likely to need, but comes with the disadvantage of price and complexity.

b. VBStats (http://peranasports.com/software/vbstatshd/) is an iPad-based scouting app developed by the Australian-based company Perana Sports. It is not quite as capable as DataVolley, but is nevertheless comprehensive (especially when used with the untan.gl apps described below). It is considerably easier to use than DataVolley, and also considerably cheaper ($50 AUD for a perpetual license).

### Analysis

#### Inbuilt

DataVolley, VBStats, and other scouting packages generally have analytical capability. This is convenient, but may be limited. DataVolley capabilities can be extended through custom worksheets, but with other packages (e.g. VBStats) you are limited to what the app provides.

#### Online apps

Alternatively, data can be exported from the scouting package and analyzed elsewhere. Science Untangled maintains a [suite of online analytical apps](https://apps.untan.gl/). They work with files scouted in DataVolley or VBStats and provide analytical capability that complements or improves on the inbuilt analytical capabilities of those packages.




